apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue
    container: green-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue
      container: green-blue
  template:
    metadata:
      labels:
        app: blue
        container: green-blue
    spec:
      containers:
      - name: blue-container
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80
