
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  labels:
    container: green-blue
spec:
  selector:
    container: green-blue
  ports:          # Map incoming port to target port
  - name: port80    # Setting multiple ports listterns
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
